[package]
name = "fip-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "fip"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
fip-core = { path = "../fip-core" }
anyhow = "1.0.98"
