[package]
name = "fip-core"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0.98"
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
mockall = "0.12.1"
tempfile = "3.10.1"
